inquiry/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('inquiry_app.urls')),
]

inquiry_app/urls.py
from django.urls import path
from inquiry_app.views import index, search, about

app_name = 'inquiry_app'

urlpatterns = [
    path('', index, name='index'),
    path('search', search, name='search'),
    path('about', about, name='about'),
]

inquiry_app/forms.py
import datetime
import re
from django import forms
from django.core.exceptions import ValidationError

SUBJECT_CHOICES = [
    ('cs', 'Computer Science'),
    ('math', 'Mathematics'),
    ('stat', 'Statistics'),
    ('physics', 'Physics'),
    ('all', 'All'),
]


class BasicSearchForm(forms.Form):
    keywords = forms.CharField(label='', max_length=100)
    subject = forms.CharField(label='', initial='all', widget=forms.Select(choices=SUBJECT_CHOICES))

    def clean(self):
        keywords = self.cleaned_data.get('keywords')
        keywords = re.sub('[^A-Za-z0-9 ]+', '', keywords)
        if not keywords:
            raise ValidationError("You must specify at least one keyword.")


class AdvancedSearchForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100, required=False)
    authors = forms.CharField(label='Authors', max_length=100, required=False)
    abstract = forms.CharField(label='Abstract', max_length=100, required=False)
    content = forms.CharField(label='Content', max_length=100, required=False)
    subject = forms.CharField(label='', initial='all',
                              widget=forms.Select(choices=SUBJECT_CHOICES), required=False)

    def clean(self):
        title = self.cleaned_data.get('title')
        title = re.sub('[^A-Za-z0-9 ]+', '', title)
        authors = self.cleaned_data.get('authors')
        authors = re.sub('[^A-Za-z0-9 ]+', '', authors)
        abstract = self.cleaned_data.get('abstract')
        abstract = re.sub('[^A-Za-z0-9 ]+', '', abstract)
        content = self.cleaned_data.get('content')
        content = re.sub('[^A-Za-z0-9 ]+', '', content)
        if not (title or authors or abstract or content):
            raise ValidationError('You must specify at least one field')

inquiry_app/views.py
from django.shortcuts import render
from inquiry_app.forms import BasicSearchForm, AdvancedSearchForm
from inquiry_app.services import InquiryService
from django.core.paginator import Paginator

# Create your views here.


def index(request):
    ctx = {'basicform': BasicSearchForm(),
           'advancedform': AdvancedSearchForm()}
    return render(request, 'index.html', ctx)


def search(request):
    service = InquiryService()
    keywords = request.GET.get('keywords')

    if request.method == 'GET':
        if keywords:
            basic_form = BasicSearchForm(request.GET)
            if basic_form.is_valid():
                result = service.search_by_keywords(basic_form.cleaned_data.get('keywords'),
                                                    basic_form.cleaned_data.get('subject'))
                result_list = [item for item in result]
                paginator = Paginator(result_list, 15)
                page = request.GET.get('page')
                result_paginated = paginator.get_page(page)
            else:
                return render(request, 'index.html', {'basicform': basic_form,
                                                      'advancedform': AdvancedSearchForm()})
        else:
            adv_form = AdvancedSearchForm(request.GET)
            if adv_form.is_valid():
                title = adv_form.cleaned_data.get('title')
                authors = adv_form.cleaned_data.get('authors')
                abstract = adv_form.cleaned_data.get('abstract')
                content = adv_form.cleaned_data.get('content')
                subject = adv_form.cleaned_data.get('subject')
                result = service.search_by_fields(title, authors, abstract, content, subject)
                result_list = [item for item in result]
                paginator = Paginator(result_list, 15)
                page = request.GET.get('page')
                result_paginated = paginator.get_page(page)
            else:
                return render(request, 'index.html', {'advancedform': adv_form,
                                                      'basicform': BasicSearchForm()})
        ctx = {'data': result_paginated, 'advancedform': AdvancedSearchForm(), 'basicform': BasicSearchForm()}
        return render(request, 'search.html', ctx)
    else:
        return render(request, 'index.html', {'basicform': basic_form, 'advancedform': adv_form})


def about(request):
    return render(request, 'about.html')

inquiry_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <title>Inquiry</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" href="{% static 'img/inquiry_logo_16.png' %}"/>
  <link rel="shortcut icon" href="{% static 'img/inquiry_logo_32.png' %}"/>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/inquiry.css' %}">

  <meta name="theme-color" content="#907faf">
</head>

<body>
  <!--[if IE]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->

  <header class="border">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'inquiry_app:index' %}">
        <img src="{% static 'img/inquiry.png' %}" alt="Inquiry Logo" width="180em" class="d-inline-block align-top">
      </a>
      {% block navbar %}{% endblock %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#inquiry_navbar" aria-controls="inquiry_navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="inquiry_navbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'inquiry_app:about' %}">About</a>
          </li>
      </div>
    </nav>
  </header>

  <main role="main">
    {% block main %}{% endblock %}
  </main>

  <div role="pagination">
    {% block paging %}{% endblock %}
  </div>

  <footer class="page-footer font-small border">
    <div class="footer-copyright text-center p-4">
      <span>Inquiry, a search engine by <a href="https://github.com/javiergarea">Javier Garea</a> and <a href="https://github.com/MartinSandeCosta">Martín Sande</a>.</span>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="{% static 'js/inquiry.js' %}"></script>
</body>

</html>

inquiry_app/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
  <div id="search-bar" class="container-fluid text-center">
    <h1 class="p-3">Open Science</h1>
    <div id="simpleSearch" class="collapse multi-collapse show">
      <form role="search" action="{% url 'inquiry_app:search' %}" method="get" class="basicform">
        <div class="input-group form-inline pb-3 justify-content-center">
          {{ basicform.subject | as_crispy_field }}
          {{ basicform.keywords | as_crispy_field }}
          <div class="custom-button">
            <button type="submit" class="btn btn-primary btn-block">Search</button>
          </div>
        </div>
      </form>
    </div>
    <div align="center">
      <div class="custom-control custom-switch col-2" data-toggle="collapse" data-target=".multi-collapse" role="button" aria-expanded="false" aria-controls="simpleSearch advancedSearch">
        <input type="checkbox" class="custom-control-input" id="customSwitches">
        <label class="custom-control-label" for="customSwitches">Advanced search</label>
      </div>
    </div>
    <div id="advancedSearch" class="collapse multi-collapse p-2">
      <form name="AdvForm" role="search" action="{% url 'inquiry_app:search' %}" method="get" class="advancedform container-fluid justify-content-center">
        <div class="d-inline-block">
            <div>{{ advancedform.title | as_crispy_field }}</div>
            <div>{{ advancedform.authors | as_crispy_field }}</div>
            <div>Subject{{ advancedform.subject | as_crispy_field }}</div>
            <div>{{ advancedform.abstract | as_crispy_field }}</div>
            <div>{{ advancedform.content | as_crispy_field }}</div>
        </div>
        <div class="col" align="center" id=alert_placeholder></div>
        <button type="submit" class="btn btn-primary" onclick="return submitform();">Search</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
      </form>
    </div>
  </div>
{% endblock %}

inquiry_app/templates/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_tags %}

{% block navbar %}
  <div class="container-fluid">
    <div class="ml-auto">
      <form role="search" action="{% url 'inquiry_app:search' %}" method="get" class="basicform">
        <div class="input-group form-inline justify-content-center">
          {{ basicform.subject | as_crispy_field }}
          {{ basicform.keywords | as_crispy_field }}
          <div class="custom-button">
            <button type="submit" class="btn btn-primary btn-block">Search</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block main %}
  <div class="p-4">
    <span class="p-2">Showing: {{ data.start_index }} to {{ data.end_index }} of {{ data.paginator.count }} results.</span>
    {% for x in data %}
      <div class="p-2">
        <div class="card">
          <div class="card-body">
            <h4><a href="{{ x.abstract_url }}" class="card-title link">{{ x.title }}</a></h4>
            <h5><a href="{{ x.pdf_url }}" class="card-link small link text-success">{{ x.pdf_url }}</a></h5>
            <h6 class="py-2 text-secondary">
              {{ x.authors | join:", " }} submitted on {{ x.submit_date | slice:"0:10" }}
            <h6>
            <div class="p-1">
              <div id="summary">
                {% if x.fragment %}
                  <p class="collapse font-italic text-justify" id="summary{{ forloop.counter }}">
                    [...]
                    {% for fragment in x.fragment %}
                      {{ fragment | safe }}
                      [...]
                    {% endfor %}
                  </p>
                {% else %}
                  <p class="collapse text-justify" id="summary{{ forloop.counter }}">
                    {{ x.abstract }}
                  </p>
                {% endif %}
                <a class="collapsed" data-toggle="collapse" href="#summary{{ forloop.counter }}" aria-expanded="false" aria-controls="summary{{ forloop.counter }}"></a>
              </div>
            </div>
            <div class="pt-1 px-1">
              <blockquote class="blockquote mb-0">
                <div class="blockquote-footer">{{ x.subject }} {%if x.other_subjects %} also {{ x.other_subjects }} {% endif %}</div> 
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    
  </div>
{% endblock %}

{% block paging %}
  <nav class="container-fluid">
    <ul class="pagination justify-content-center">
      {% if data.has_previous %}
        <li class="page-item">
          <a class="page-link" href="{% url 'inquiry_app:search' %}?{{ request.GET.urlencode | remove_page }}&page=1" aria-label="First">
            <span>First</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'inquiry_app:search' %}?{{ request.GET.urlencode | remove_page }}&page={{ data.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}
      <li class="page-item">
          <a class="page-link text-primary"><span>Page {{ data.number }} of {{ data.paginator.num_pages }}</span></a>
      </li>
      {% if data.has_next %}
        <li class="page-item">
          <a class="page-link" href="{% url 'inquiry_app:search' %}?{{ request.GET.urlencode | remove_page }}&page={{ data.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'inquiry_app:search' %}?{{ request.GET.urlencode | remove_page }}&page={{ data.paginator.num_pages }}" aria-label="Last">
            <span>Last</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock %}